### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Marken23** [islamshahil/Text-To-SQL-Using-GPT-3#1]
1) ImportError: cannot import name 'GPT'

2) Can I remove these lines?
# import json
# import openai

# with open('GPT_SECRET_KEY.json') as f:
#     data = json.load(f)

# openai.api_key = data["API_KEY"]

Best regards

**Comment by themightywolfie** [comment]
No you can't remove these lines because they are the most important ones. The owner of this repo didn't include any other dependencies or instructions on how to run this program
Go to this repo https://github.com/shreyashankar/gpt3-sandbox and then go to the api folder and copy the code from gpt.py into a file of the same name. 

Go to your command prompt and type `pip install json` and then `pip install openai`

Make a json file in the clone directory of this repo and put your API Key from Open AI in that file. 

 If you want I can fork this repo and the necessary files to run it with instructions.

**Comment by islamshahil** [comment]
This is a incomplete project, when I was working, Open Ai wasn't providing any api keys. Feel free to complete the project and also create a request, I'll merge it.
